version: '3.5'

services:
  morningDb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS_MORNING}
      - POSTGRES_DB=${DB_NAME_MORNING}
    container_name: morning-postgres
    volumes:
      - ./pgdata/morning:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    env_file:
      - .env

  afternoonDb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS_AFTERNOON}
      - POSTGRES_DB=${DB_NAME_AFTERNOON}
    container_name: afternoon-postgres
    volumes:
      - ./pgdata/afternoon:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    env_file:
      - .env

  mongodb:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - '27017:27017'
    volumes:
      - ./mongodata:/data/db
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - morningDb
      - afternoonDb
      - mongodb
      - redis
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - morningDb
      - afternoonDb
    env_file:
      - .env

volumes:
  morning_pgdata:
  afternoon_pgdata:
  mongodata:
